USE [SPRING_DEMO]
GO

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 3/14/2017 10:29:04 AM ******/

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 3/14/2017 10:29:04 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_NAME] [nvarchar](50) NULL,
	[EMP_ADDRESS] [nvarchar](50) NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

